# Generated by Django 5.0.14 on 2025-06-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('MD', 'MD'), ('OPS MANAGER', 'Ops Manager'), ('FINANCE MANAGER', 'Finance Manager'), ('HSSE MANAGER', 'HSSE Manager'), ('TECHNICIAN', 'Technician')], default='TECHNICIAN', max_length=20, null=True, verbose_name='position'),
        ),
    ]
