# Generated by Django 5.0.14 on 2025-07-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('MD', 'MD'), ('OPS MANAGER', 'Ops Manager'), ('FINANCE MANAGER', 'Finance Manager'), ('HSSE MANAGER', 'HSSE Manager'), ('TECHNICIAN', 'Technician'), ('GENERAL STAFF', 'General Staff')], default='TECHNICIAN', max_length=20, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=10, verbose_name='role'),
        ),
    ]
