from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api.views import (
    DocumentListCreateAPIView,
    DocumentRetrieveUpdateDestroyAPIView,
    ISOClauseListCreateAPIView,
    TagListCreateAPIView,
    ChangeRequestListCreateAPIView,
    VerifyDocumentAPIView,
    ApproveDocumentAPIView,
    RejectDocumentAPIView,
    SubmitDocumentAPIView,
    DocumentWorkflowHistoryAPIView,
    CreateNewVersionAPIView,
    DocumentTemplateListCreateAPIView,
    DocumentTemplateRetrieveUpdateDestroyAPIView,
    CreateDocumentFromTemplateAPIView,
    ApproveTemplateAPIView,
    ChangeRequestApproveAPIView,
    ChangeRequestRejectAPIView,
    SubmitForOpsReviewAPIView,
    OpsReviewAPIView,
    MDApprovalAPIView,
    RecordViewSet,
    LawCategoryListCreateAPIView,
    LawCategoryRetrieveUpdateDestroyAPIView,
    LawResourceListCreateAPIView,
    LawResourceRetrieveUpdateDestroyAPIView,
    LawResourceChangeListCreateAPIView,
    LawResourceChangeRetrieveUpdateDestroyAPIView,
    LegalRegisterEntryListCreateAPIView,
    LegalRegisterEntryRetrieveUpdateDestroyAPIView,
    LegalRegisterCommentListCreateAPIView,
    LegalRegisterCommentRetrieveUpdateDestroyAPIView,
    LegalRegisterDocumentListCreateAPIView,
    LegalRegisterDocumentRetrieveUpdateDestroyAPIView,
    PositionListCreateAPIView, PositionRetrieveUpdateDestroyAPIView,
    LegislationTrackerListCreateAPIView, LegislationTrackerRetrieveUpdateDestroyAPIView,
)

# Router for ViewSets
router = DefaultRouter()
router.register(r'records', RecordViewSet, basename='record')

urlpatterns = [
    path('documents/', DocumentListCreateAPIView.as_view(), name='document-list-create'),
    path('documents/<uuid:pk>/', DocumentRetrieveUpdateDestroyAPIView.as_view(), name='document-retrieve-update-destroy'),
    path('documents/iso-clauses/', ISOClauseListCreateAPIView.as_view(), name='iso-clause-list-create'),
    path('documents/tags/', TagListCreateAPIView.as_view(), name='tag-list-create'),
    path('documents/change-requests/', ChangeRequestListCreateAPIView.as_view(), name='change-request-list-create'),
    path('documents/verify/', VerifyDocumentAPIView.as_view(), name='document-verify'),
    path('documents/approve/', ApproveDocumentAPIView.as_view(), name='document-approve'),
    path('documents/reject/', RejectDocumentAPIView.as_view(), name='document-reject'),
    path('documents/submit/', SubmitDocumentAPIView.as_view(), name='document-submit'),
    path('documents/<uuid:pk>/workflow-history/', DocumentWorkflowHistoryAPIView.as_view(), name='document-workflow-history'),
    path('documents/<uuid:pk>/new-version/', CreateNewVersionAPIView.as_view(), name='document-new-version'),
    path('templates/', DocumentTemplateListCreateAPIView.as_view(), name='template-list-create'),
    path('templates/<int:pk>/', DocumentTemplateRetrieveUpdateDestroyAPIView.as_view(), name='template-retrieve-update-destroy'),
    path('templates/<int:pk>/create-document/', CreateDocumentFromTemplateAPIView.as_view(), name='template-create-document'),
    path('templates/<int:pk>/approve/', ApproveTemplateAPIView.as_view(), name='template-approve'),
    path('change-requests/<int:pk>/approve/', ChangeRequestApproveAPIView.as_view(), name='change-request-approve'),
    path('change-requests/<int:pk>/reject/', ChangeRequestRejectAPIView.as_view(), name='change-request-reject'),
    path('documents/<uuid:pk>/submit-for-ops-review/', SubmitForOpsReviewAPIView.as_view(), name='document-submit-for-ops-review'),
    path('documents/<uuid:pk>/ops-review/', OpsReviewAPIView.as_view(), name='document-ops-review'),
    path('documents/<uuid:pk>/md-approval/', MDApprovalAPIView.as_view(), name='document-md-approval'),
    path('legals/categories/', LawCategoryListCreateAPIView.as_view(), name='lawcategory-list-create'),
    path('legals/categories/<int:pk>/', LawCategoryRetrieveUpdateDestroyAPIView.as_view(), name='lawcategory-detail'),
    path('legals/resources/', LawResourceListCreateAPIView.as_view(), name='lawresource-list-create'),
    path('legals/resources/<int:pk>/', LawResourceRetrieveUpdateDestroyAPIView.as_view(), name='lawresource-detail'),
    path('legals/resource-changes/', LawResourceChangeListCreateAPIView.as_view(), name='lawresourcechange-list-create'),
    path('legals/resource-changes/<int:pk>/', LawResourceChangeRetrieveUpdateDestroyAPIView.as_view(), name='lawresourcechange-detail'),
    path('legals/register-entries/', LegalRegisterEntryListCreateAPIView.as_view(), name='legalregisterentry-list-create'),
    path('legals/register-entries/<int:pk>/', LegalRegisterEntryRetrieveUpdateDestroyAPIView.as_view(), name='legalregisterentry-detail'),
    path('legals/register-comments/', LegalRegisterCommentListCreateAPIView.as_view(), name='legalregistercomment-list-create'),
    path('legals/register-comments/<int:pk>/', LegalRegisterCommentRetrieveUpdateDestroyAPIView.as_view(), name='legalregistercomment-detail'),
    path('legals/register-documents/', LegalRegisterDocumentListCreateAPIView.as_view(), name='legalregisterdocument-list-create'),
    path('legals/register-documents/<int:pk>/', LegalRegisterDocumentRetrieveUpdateDestroyAPIView.as_view(), name='legalregisterdocument-detail'),
    path('legals/positions/', PositionListCreateAPIView.as_view(), name='position-list-create'),
    path('legals/positions/<int:pk>/', PositionRetrieveUpdateDestroyAPIView.as_view(), name='position-detail'),
    path('legals/legislation-trackers/', LegislationTrackerListCreateAPIView.as_view(), name='legislationtracker-list-create'),
    path('legals/legislation-trackers/<int:pk>/', LegislationTrackerRetrieveUpdateDestroyAPIView.as_view(), name='legislationtracker-detail'),
    path('', include(router.urls)),
]
