# Generated by Django 5.0.14 on 2025-10-16 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditplan',
            name='audit_criteria',
            field=models.TextField(blank=True, help_text='Standards, regulations, procedures against which audit is conducted'),
        ),
        migrations.AlterField(
            model_name='auditplan',
            name='departments',
            field=models.JSONField(blank=True, default=list, help_text='List of departments to audit'),
        ),
        migrations.AlterField(
            model_name='auditplan',
            name='lead_auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_led', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditplan',
            name='locations',
            field=models.JSONField(blank=True, default=list, help_text='Physical locations to audit'),
        ),
        migrations.AlterField(
            model_name='auditplan',
            name='methodology',
            field=models.JSONField(blank=True, default=dict, help_text='Audit methodology: interviews, document review, observations, etc.'),
        ),
        migrations.AlterField(
            model_name='auditplan',
            name='objectives',
            field=models.JSONField(blank=True, default=list, help_text='List of audit objectives'),
        ),
        migrations.AlterField(
            model_name='auditplan',
            name='processes',
            field=models.JSONField(blank=True, default=list, help_text='List of processes to audit'),
        ),
        migrations.AlterField(
            model_name='auditplan',
            name='scope_description',
            field=models.TextField(blank=True, help_text='Detailed audit scope'),
        ),
    ]
