# Generated by Django 5.0.14 on 2025-10-17 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_finalize_audit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChecklistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(help_text='e.g., 1, 2, 3')),
                ('category_name', models.CharField(help_text="e.g., 'Leadership & HSSE Culture'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Audit Checklist Category',
                'verbose_name_plural': 'Audit Checklist Categories',
                'ordering': ['template', 'order', 'section_number'],
            },
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='attendees',
            field=models.JSONField(blank=True, default=list, help_text='List of attendee names present during audit'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='audit_date',
            field=models.DateField(blank=True, help_text='Date when the audit was conducted', null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='checklist_responses',
            field=models.JSONField(blank=True, default=dict, help_text='Responses to checklist questions'),
        ),
        migrations.CreateModel(
            name='AuditChecklistQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_name', models.CharField(blank=True, help_text="e.g., 'Commitment to HSE'", max_length=255)),
                ('reference_number', models.CharField(help_text="e.g., '1.1', '2.1'", max_length=20)),
                ('question_letter', models.CharField(help_text="e.g., 'a', 'b', 'c'", max_length=10)),
                ('question_text', models.TextField(help_text='The actual question')),
                ('expected_response_type', models.CharField(choices=[('TEXT', 'Text'), ('YES_NO', 'Yes/No'), ('RATING', 'Rating (1-5)'), ('FILE', 'File Upload'), ('MULTI_TEXT', 'Multiple Text Fields')], default='TEXT', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('help_text', models.TextField(blank=True, help_text='Additional guidance for auditors')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='audits.auditchecklistcategory')),
            ],
            options={
                'verbose_name': 'Audit Checklist Question',
                'verbose_name_plural': 'Audit Checklist Questions',
                'ordering': ['category', 'order', 'reference_number', 'question_letter'],
                'unique_together': {('category', 'reference_number', 'question_letter')},
            },
        ),
        migrations.CreateModel(
            name='AuditChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'System Audit Checklist v1.0'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='audits.audittype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Checklist Template',
                'verbose_name_plural': 'Audit Checklist Templates',
                'ordering': ['audit_type', '-version'],
                'unique_together': {('audit_type', 'version')},
            },
        ),
        migrations.AddField(
            model_name='auditchecklistcategory',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='audits.auditchecklisttemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='auditchecklistcategory',
            unique_together={('template', 'section_number')},
        ),
        migrations.CreateModel(
            name='AuditQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, help_text='Answer to the question')),
                ('compliance_status', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant'), ('OBSERVATION', 'Observation'), ('NOT_APPLICABLE', 'Not Applicable'), ('OPPORTUNITY', 'Opportunity for Improvement')], default='COMPLIANT', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations')),
                ('evidence_files', models.JSONField(blank=True, default=list, help_text='List of evidence file URLs/paths')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='audits.auditfinding')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='audits.auditchecklistquestion')),
            ],
            options={
                'verbose_name': 'Audit Question Response',
                'verbose_name_plural': 'Audit Question Responses',
                'ordering': ['question__order'],
                'unique_together': {('finding', 'question')},
            },
        ),
    ]
