# Generated by Django 5.0.14 on 2025-10-17 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_auditchecklistcategory_auditfinding_attendees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditScoringCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('OFI', 'Opportunity for Improvement'), ('MINOR_NC', 'Minor Non-Conformity'), ('MAJOR_NC', 'Major Non-Conformity')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('color_code', models.CharField(help_text='GREEN, YELLOW, ORANGE, RED', max_length=20)),
                ('score_percentage', models.DecimalField(decimal_places=2, help_text='Score contribution (0-100%)', max_digits=5)),
                ('definition', models.TextField(help_text='Industry standard definition')),
                ('action_required', models.TextField(help_text='Required action for this finding type')),
                ('examples', models.TextField(blank=True, help_text='Examples of this finding type')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Audit Scoring Criteria',
                'verbose_name_plural': 'Audit Scoring Criteria',
                'ordering': ['-score_percentage'],
            },
        ),
        migrations.AddField(
            model_name='auditchecklistcategory',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Category weight in % (all categories must sum to 100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='auditchecklistquestion',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Question weight in % within category (all questions in category must sum to 100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
