# Generated by Django 5.0.14 on 2025-06-24 16:59

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegislationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit', models.CharField(max_length=255)),
                ('issuing_authority', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=255)),
                ('date_of_issue', models.DateField()),
                ('expiring_date', models.DateField()),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired')], max_length=20)),
                ('action_taken', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='legislation_tracker/evidence/')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LawResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('jurisdiction', models.CharField(choices=[('district', 'District'), ('local', 'Local Authority'), ('national', 'National'), ('industrial', 'Industrial')], max_length=20)),
                ('is_repealed', models.BooleanField(default=False)),
                ('document', models.FileField(upload_to='law_library/')),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='legals.lawcategory')),
            ],
        ),
        migrations.CreateModel(
            name='LawResourceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_description', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='legals.lawresource')),
            ],
        ),
        migrations.CreateModel(
            name='LegalRegisterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('regulatory_requirement', models.TextField()),
                ('owner_department', models.CharField(choices=[('OPERATIONS', 'Operations'), ('MARKETING', 'Marketing'), ('HSSE', 'HSSE'), ('FINANCE', 'Finance')], default='OPERATIONS', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('action', models.TextField(default='No action specified')),
                ('evaluation_compliance', models.TextField()),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('non-compliant', 'Non-compliant'), ('partial', 'Partial')], max_length=20)),
                ('further_actions', models.TextField(blank=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('category', models.CharField(max_length=100)),
                ('legal_obligation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legislation_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_register_entries', to='legals.lawresource')),
                ('related_legislation', models.ManyToManyField(blank=True, related_name='related_entries', to='legals.lawresource')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='legal_register_assignments', to='legals.position')),
            ],
        ),
        migrations.CreateModel(
            name='LegalRegisterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='legal_register/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='legals.legalregisterentry')),
            ],
        ),
        migrations.CreateModel(
            name='LegalRegisterComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='legals.legalregisterentry')),
            ],
        ),
    ]
