# Generated by Django 5.0.14 on 2025-08-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawcategory',
            options={'verbose_name': 'Law Category', 'verbose_name_plural': 'Law Categories'},
        ),
        migrations.AlterField(
            model_name='lawcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
