# Generated by Django 5.0.14 on 2025-10-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legals', '0008_fix_is_archived_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawresource',
            name='act_number',
            field=models.CharField(blank=True, help_text='Official Act/Law number', max_length=100),
        ),
        migrations.AlterField(
            model_name='lawresource',
            name='amendment_history',
            field=models.TextField(blank=True, help_text='History of amendments'),
        ),
        migrations.AlterField(
            model_name='lawresource',
            name='applicability',
            field=models.TextField(blank=True, help_text='Who/what this law applies to'),
        ),
        migrations.AlterField(
            model_name='lawresource',
            name='authority_contact',
            field=models.CharField(blank=True, help_text='Contact information', max_length=255),
        ),
        migrations.AlterField(
            model_name='lawresource',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='law_library/'),
        ),
        migrations.AlterField(
            model_name='lawresource',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Date when law became effective', null=True),
        ),
        migrations.AlterField(
            model_name='lawresource',
            name='enactment_date',
            field=models.DateField(blank=True, help_text='Date when law was enacted', null=True),
        ),
        migrations.AlterField(
            model_name='lawresource',
            name='enforcement_authority',
            field=models.CharField(blank=True, help_text='Authority responsible for enforcement', max_length=255),
        ),
        migrations.AlterField(
            model_name='lawresource',
            name='key_provisions',
            field=models.TextField(blank=True, help_text='Key provisions and requirements'),
        ),
        migrations.AlterField(
            model_name='legalregisterdocument',
            name='document_type',
            field=models.CharField(blank=True, help_text='Type of evidence', max_length=50),
        ),
    ]
