# Generated by Django 5.0.14 on 2025-07-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppepurchase',
            name='receipt_document',
            field=models.FileField(blank=True, null=True, upload_to='ppe_purchase_receipts/'),
        ),
        migrations.AlterField(
            model_name='ppepurchase',
            name='purchase_order_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
