# Generated by Django 5.0.14 on 2025-06-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, help_text='Document content for inline editing'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('POLICY', 'Policy'), ('SYSTEM DOCUMENT', 'System Document'), ('PROCEDURE', 'Procedure'), ('FORM', 'Form'), ('SSOW', 'SSOW'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='document_type',
            field=models.CharField(choices=[('POLICY', 'Policy'), ('SYSTEM DOCUMENT', 'System Document'), ('PROCEDURE', 'Procedure'), ('FORM', 'Form'), ('SSOW', 'SSOW'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
