# Generated by Django 5.0.14 on 2025-06-21 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_content_alter_document_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests_responded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('HSSE_REVIEW', 'HSSE Manager Review'), ('OPS_REVIEW', 'OPS Manager Review'), ('MD_APPROVAL', 'MD Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('UPLOAD', 'File Upload Template'), ('IN_APP', 'In-App Form Template')], default='UPLOAD', max_length=10)),
                ('file', models.FileField(blank=True, help_text='Uploadable template file (e.g., Word, PDF)', null=True, upload_to='form_templates/')),
                ('form_schema', models.JSONField(blank=True, default=dict, help_text='JSON schema for building the form in the frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_file', models.FileField(blank=True, null=True, upload_to='records/%Y/%m/')),
                ('submitted_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='documents.formtemplate')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
