# Generated by Django 5.0.14 on 2025-06-22 11:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_changerequest_responded_by_and_more'),
    ]

    operations = [
        # Remove template_type and form_schema fields from FormTemplate
        migrations.RemoveField(
            model_name='formtemplate',
            name='template_type',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='form_schema',
        ),
        
        # Make file field non-nullable in FormTemplate
        migrations.AlterField(
            model_name='formtemplate',
            name='file',
            field=models.FileField(help_text='Uploadable template file (Word, PDF, Excel)', upload_to='form_templates/'),
        ),
        
        # Remove submitted_data field from Record
        migrations.RemoveField(
            model_name='record',
            name='submitted_data',
        ),
        
        # Make submitted_file field non-nullable in Record
        migrations.AlterField(
            model_name='record',
            name='submitted_file',
            field=models.FileField(upload_to='records/%Y/%m/'),
        ),
    ]
