# Generated by Django 5.0.14 on 2025-07-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20250622_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalworkflow',
            name='position',
            field=models.CharField(choices=[('MD', 'MD'), ('OPS MANAGER', 'Ops Manager'), ('FINANCE MANAGER', 'Finance Manager'), ('HSSE MANAGER', 'HSSE Manager'), ('TECHNICIAN', 'Technician'), ('GENERAL STAFF', 'General Staff')], max_length=20),
        ),
    ]
