# Generated by Django 5.0.14 on 2025-10-31 17:11

from django.db import migrations


def populate_initial_folders(apps, schema_editor):
    """Create initial folders for existing document types."""
    DocumentFolder = apps.get_model('documents', 'DocumentFolder')
    User = apps.get_model('accounts', 'User')
    
    # Default folders matching existing DOC_TYPES
    initial_folders = [
        {'name': 'Policy', 'value': 'POLICY'},
        {'name': 'System Document', 'value': 'SYSTEM_DOCUMENT'},
        {'name': 'Procedure', 'value': 'PROCEDURE'},
        {'name': 'Form', 'value': 'FORM'},
        {'name': 'SSOW', 'value': 'SSOW'},
        {'name': 'Other', 'value': 'OTHER'},
    ]
    
    # Get first superuser or HSSE Manager as creator, or None
    creator = None
    try:
        from django.db.models import Q
        creator = User.objects.filter(
            Q(is_superuser=True) | Q(position='HSSE MANAGER')
        ).first()
    except:
        pass
    
    for folder_data in initial_folders:
        # Normalize value: SYSTEM DOCUMENT -> SYSTEM_DOCUMENT
        value = folder_data['value']
        if not DocumentFolder.objects.filter(value=value).exists():
            DocumentFolder.objects.create(
                name=folder_data['name'],
                value=value,
                created_by=creator,
                is_active=True
            )


def reverse_populate_initial_folders(apps, schema_editor):
    """Remove initial folders."""
    DocumentFolder = apps.get_model('documents', 'DocumentFolder')
    DocumentFolder.objects.filter(value__in=[
        'POLICY', 'SYSTEM_DOCUMENT', 'PROCEDURE', 'FORM', 'SSOW', 'OTHER'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_add_document_folder'),
    ]

    operations = [
        migrations.RunPython(populate_initial_folders, reverse_populate_initial_folders),
    ]
