# Generated by Django 5.0.14 on 2025-11-05 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_populate_initial_folders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='record',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='record_number',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated: REC-YYYY-NNN', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='record',
            name='year',
            field=models.IntegerField(blank=True, editable=False, help_text='Year of submission for categorization', null=True),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['year', 'status'], name='documents_r_year_6cbc61_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['submitted_by', 'year'], name='documents_r_submitt_8de6f9_idx'),
        ),
    ]
