# Generated by Django 5.0.14 on 2025-11-05 13:15

from django.db import migrations


def populate_record_numbers_and_years(apps, schema_editor):
    """Populate year and record_number for existing records."""
    Record = apps.get_model('documents', 'Record')
    
    # Get all records ordered by created_at
    records = Record.objects.all().order_by('created_at')
    
    # Group by year and assign record numbers
    year_counters = {}
    
    for record in records:
        # Set year from created_at
        year = record.created_at.year
        record.year = year
        
        # Generate record number if not set
        if not record.record_number:
            if year not in year_counters:
                year_counters[year] = 1
            else:
                year_counters[year] += 1
            
            record.record_number = f"REC-{year}-{year_counters[year]:03d}"
        
        # Save without triggering the save() method logic
        Record.objects.filter(pk=record.pk).update(
            year=record.year,
            record_number=record.record_number
        )


def reverse_populate(apps, schema_editor):
    """Reverse migration - set to null."""
    Record = apps.get_model('documents', 'Record')
    Record.objects.all().update(year=None, record_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_enhance_records_with_year_and_notifications'),
    ]

    operations = [
        migrations.RunPython(populate_record_numbers_and_years, reverse_populate),
    ]
