# Generated by Django 5.0.14 on 2025-11-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_populate_record_numbers_and_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional: Additional notes or comments'),
        ),
        migrations.AddField(
            model_name='record',
            name='title',
            field=models.CharField(blank=True, help_text='Optional: Custom name for this record submission', max_length=255),
        ),
    ]
