# Generated by Django 5.0.14 on 2025-11-05 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_add_title_and_notes_to_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='form_document',
            field=models.ForeignKey(blank=True, limit_choices_to={'document_type': 'FORM'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='documents.document'),
        ),
    ]
