# Generated by Django 5.0.14 on 2025-11-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_make_form_document_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(help_text='Descriptive name for this record submission', max_length=255),
        ),
    ]
