# Generated by Django 5.0.14 on 2026-01-28 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_add_iso45001_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='department',
            field=models.CharField(blank=True, choices=[('OPERATIONS', 'Operations'), ('MARKETING', 'Marketing'), ('HSSE', 'HSSE'), ('FINANCE', 'Finance')], help_text='Department that created this record', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='form_document',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use source_document instead. Kept for backward compatibility.', limit_choices_to={'document_type': 'FORM'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='documents.document'),
        ),
    ]
