# Generated by Django 5.0.14 on 2025-11-05 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0013_make_title_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_number', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('report_type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('NEAR_MISS', 'Near Miss'), ('POTENTIAL_INCIDENT', 'Potential Incident'), ('NON_CONFORMITY', 'Non-Conformity')], max_length=20)),
                ('title', models.CharField(help_text='Brief description of the incident', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of what happened')),
                ('location', models.CharField(help_text='Where did this occur?', max_length=255)),
                ('incident_date', models.DateTimeField(help_text='When did this occur?')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('persons_involved', models.TextField(blank=True, help_text='Names of people involved (if any)')),
                ('witnesses', models.TextField(blank=True, help_text='Names of witnesses (if any)')),
                ('immediate_actions_taken', models.TextField(blank=True, help_text='What was done immediately after the incident?')),
                ('contributing_factors', models.TextField(blank=True, help_text='What factors contributed to this incident?')),
                ('photo_evidence', models.FileField(blank=True, null=True, upload_to='quick_reports/photos/%Y/%m/')),
                ('additional_document', models.FileField(blank=True, null=True, upload_to='quick_reports/documents/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quick_report', to='documents.record')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', 'status'], name='quickreport_report__e5da7a_idx'), models.Index(fields=['reported_by', 'created_at'], name='quickreport_reporte_d036b7_idx'), models.Index(fields=['incident_date'], name='quickreport_inciden_3abbec_idx')],
            },
        ),
    ]
